### ISSUE TITLE
Please Kind request

### ISSUE THREAD

**Issue by oscarmh** [slawek87/geolocation-python#32]
Hi, using your library can I kindly ask for a sample on this https://developers.google.com/maps/documentation/geolocation/intro ?
Best regards

I,m using something like this in the input

{
  "cellTowers": [
    {
      "cellId": 21532831,
      "locationAreaCode": 2862,
      "mobileCountryCode": 214,
      "mobileNetworkCode": 7
    }
  ]
}

**Comment by slawek87** [comment]
Hey Oscar!

Geolocation doesn’t support this this endpoint. I can implement it in new version :) What is your deadline?

Sławek
