### ISSUE TITLE
Does't work for Google GEO replies only with sublocality (without city)

### ISSUE THREAD

**Issue by evgenosiptsov** [slawek87/geolocation-python#33]
Hello! 

There are a lot of geo params for Airport query, but a lot of geolocation-python decoding results are without locations. It happens because validation func does not pass locations without city.

For example:
https://maps.googleapis.com/maps/api/geocode/json?address=United%20States%20New%20York%20John%20F%20Kennedy%20International%20Airport

Google return «sublocality» for JFK and does not have any data about «city». 
Sometimes it happens. I do recommend make validation by more than one param. I did it because for me it working correct.

I thank you for your service ) Eugene

**Comment by slawek87** [comment]
Hello! :)

Let’s do that together! :) I’ll team work :) maybe you can start from creating new branch for that thing?

Sławek

**Comment by evgenosiptsov** [comment]
Yes! Nice idea, for the next few days I would make new branch.
