### ISSUE TITLE
Problem with Google maps geolocation API key

### ISSUE THREAD

**Issue by JorgeMarinC** [slawek87/geolocation-python#34]
As i have seen in the example codes,  i made a function to take the exactly latitude and longitude, taking the adress as a parameter.

def geo_codificacion(direccion):
    
    address=direccion
    google_maps = GoogleMaps(api_key='My_API_key' )
    location = google_maps.search(location=address)
    my_location = location.first()
    
    latitud=my_location.lat
    longitud=my_location.lng
    res=[latitud,longitud]
    
    return res
But it isnt using the api key, so i tried to put the api key directly on the example code with same result.

**Comment by slawek87** [comment]
You don't need to use api_key. Without API_KEY you will get lower requests limit to Google MAPS API.
